/**
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by scripts/generate-registry.mjs
 * Run `npm run generate` to regenerate.
 */

export interface ComponentEntry {
  slug: string
  name: string
  category: string
  hasStories: boolean
}

export interface IconEntry {
  fileName: string
  importName: string
}

export const componentRegistry: ComponentEntry[] = [
  {
    "slug": "alert",
    "name": "Alert",
    "category": "Retroalimentacion",
    "hasStories": true
  },
  {
    "slug": "avatar",
    "name": "Avatar",
    "category": "Visualizacion de datos",
    "hasStories": true
  },
  {
    "slug": "badge",
    "name": "Badge",
    "category": "Visualizacion de datos",
    "hasStories": true
  },
  {
    "slug": "button",
    "name": "Button",
    "category": "Formularios",
    "hasStories": true
  },
  {
    "slug": "calendar",
    "name": "Calendar",
    "category": "Visualizacion de datos",
    "hasStories": true
  },
  {
    "slug": "checkbox",
    "name": "Checkbox",
    "category": "Formularios",
    "hasStories": true
  },
  {
    "slug": "code",
    "name": "Code",
    "category": "Tipografia",
    "hasStories": true
  },
  {
    "slug": "code-block",
    "name": "CodeBlock",
    "category": "Tipografia",
    "hasStories": true
  },
  {
    "slug": "command",
    "name": "Command",
    "category": "Superposiciones",
    "hasStories": true
  },
  {
    "slug": "command-bar",
    "name": "CommandBar",
    "category": "Superposiciones",
    "hasStories": true
  },
  {
    "slug": "container",
    "name": "Container",
    "category": "Disposicion",
    "hasStories": true
  },
  {
    "slug": "copy",
    "name": "Copy",
    "category": "Visualizacion de datos",
    "hasStories": true
  },
  {
    "slug": "currency-input",
    "name": "CurrencyInput",
    "category": "Formularios",
    "hasStories": true
  },
  {
    "slug": "date-picker",
    "name": "DatePicker",
    "category": "Formularios",
    "hasStories": true
  },
  {
    "slug": "divider",
    "name": "Divider",
    "category": "Disposicion",
    "hasStories": true
  },
  {
    "slug": "drawer",
    "name": "Drawer",
    "category": "Superposiciones",
    "hasStories": true
  },
  {
    "slug": "dropdown-menu",
    "name": "DropdownMenu",
    "category": "Superposiciones",
    "hasStories": true
  },
  {
    "slug": "focus-modal",
    "name": "FocusModal",
    "category": "Superposiciones",
    "hasStories": true
  },
  {
    "slug": "heading",
    "name": "Heading",
    "category": "Tipografia",
    "hasStories": true
  },
  {
    "slug": "hint",
    "name": "Hint",
    "category": "Formularios",
    "hasStories": true
  },
  {
    "slug": "i18n-provider",
    "name": "I18nProvider",
    "category": "Proveedores",
    "hasStories": false
  },
  {
    "slug": "icon-badge",
    "name": "IconBadge",
    "category": "Visualizacion de datos",
    "hasStories": true
  },
  {
    "slug": "icon-button",
    "name": "IconButton",
    "category": "Formularios",
    "hasStories": true
  },
  {
    "slug": "inline-tip",
    "name": "InlineTip",
    "category": "Retroalimentacion",
    "hasStories": true
  },
  {
    "slug": "input",
    "name": "Input",
    "category": "Formularios",
    "hasStories": true
  },
  {
    "slug": "kbd",
    "name": "Kbd",
    "category": "Tipografia",
    "hasStories": true
  },
  {
    "slug": "label",
    "name": "Label",
    "category": "Formularios",
    "hasStories": true
  },
  {
    "slug": "popover",
    "name": "Popover",
    "category": "Superposiciones",
    "hasStories": false
  },
  {
    "slug": "progress-accordion",
    "name": "ProgressAccordion",
    "category": "Navegacion",
    "hasStories": true
  },
  {
    "slug": "progress-tabs",
    "name": "ProgressTabs",
    "category": "Navegacion",
    "hasStories": true
  },
  {
    "slug": "prompt",
    "name": "Prompt",
    "category": "Superposiciones",
    "hasStories": true
  },
  {
    "slug": "radio-group",
    "name": "RadioGroup",
    "category": "Formularios",
    "hasStories": true
  },
  {
    "slug": "select",
    "name": "Select",
    "category": "Formularios",
    "hasStories": true
  },
  {
    "slug": "skeleton",
    "name": "Skeleton",
    "category": "Retroalimentacion",
    "hasStories": false
  },
  {
    "slug": "status-badge",
    "name": "StatusBadge",
    "category": "Visualizacion de datos",
    "hasStories": true
  },
  {
    "slug": "switch",
    "name": "Switch",
    "category": "Formularios",
    "hasStories": true
  },
  {
    "slug": "table",
    "name": "Table",
    "category": "Visualizacion de datos",
    "hasStories": true
  },
  {
    "slug": "tabs",
    "name": "Tabs",
    "category": "Navegacion",
    "hasStories": true
  },
  {
    "slug": "text",
    "name": "Text",
    "category": "Tipografia",
    "hasStories": true
  },
  {
    "slug": "textarea",
    "name": "Textarea",
    "category": "Formularios",
    "hasStories": true
  },
  {
    "slug": "toast",
    "name": "Toast",
    "category": "Retroalimentacion",
    "hasStories": true
  },
  {
    "slug": "toaster",
    "name": "Toaster",
    "category": "Retroalimentacion",
    "hasStories": true
  },
  {
    "slug": "tooltip",
    "name": "Tooltip",
    "category": "Superposiciones",
    "hasStories": true
  }
]

export const iconRegistry: IconEntry[] = [
  {
    "fileName": "WIP",
    "importName": "WIP"
  },
  {
    "fileName": "academic-cap-solid",
    "importName": "AcademicCapSolid"
  },
  {
    "fileName": "academic-cap",
    "importName": "AcademicCap"
  },
  {
    "fileName": "adjustments-done",
    "importName": "AdjustmentsDone"
  },
  {
    "fileName": "adjustments",
    "importName": "Adjustments"
  },
  {
    "fileName": "ai-assistent-luminosity",
    "importName": "AiAssistentLuminosity"
  },
  {
    "fileName": "ai-assistent",
    "importName": "AiAssistent"
  },
  {
    "fileName": "amazon",
    "importName": "Amazon"
  },
  {
    "fileName": "americo",
    "importName": "Americo"
  },
  {
    "fileName": "apple",
    "importName": "Apple"
  },
  {
    "fileName": "archive-box",
    "importName": "ArchiveBox"
  },
  {
    "fileName": "arrow-down-circle",
    "importName": "ArrowDownCircle"
  },
  {
    "fileName": "arrow-down-left-mini",
    "importName": "ArrowDownLeftMini"
  },
  {
    "fileName": "arrow-down-left",
    "importName": "ArrowDownLeft"
  },
  {
    "fileName": "arrow-down-mini",
    "importName": "ArrowDownMini"
  },
  {
    "fileName": "arrow-down-right-mini",
    "importName": "ArrowDownRightMini"
  },
  {
    "fileName": "arrow-down-tray",
    "importName": "ArrowDownTray"
  },
  {
    "fileName": "arrow-down",
    "importName": "ArrowDown"
  },
  {
    "fileName": "arrow-left-mini",
    "importName": "ArrowLeftMini"
  },
  {
    "fileName": "arrow-left",
    "importName": "ArrowLeft"
  },
  {
    "fileName": "arrow-long-down",
    "importName": "ArrowLongDown"
  },
  {
    "fileName": "arrow-long-left",
    "importName": "ArrowLongLeft"
  },
  {
    "fileName": "arrow-long-right",
    "importName": "ArrowLongRight"
  },
  {
    "fileName": "arrow-long-up",
    "importName": "ArrowLongUp"
  },
  {
    "fileName": "arrow-path-mini",
    "importName": "ArrowPathMini"
  },
  {
    "fileName": "arrow-path",
    "importName": "ArrowPath"
  },
  {
    "fileName": "arrow-right-down",
    "importName": "ArrowRightDown"
  },
  {
    "fileName": "arrow-right-mini",
    "importName": "ArrowRightMini"
  },
  {
    "fileName": "arrow-right-on-rectangle",
    "importName": "ArrowRightOnRectangle"
  },
  {
    "fileName": "arrow-right",
    "importName": "ArrowRight"
  },
  {
    "fileName": "arrow-turn-up",
    "importName": "ArrowTurnUp"
  },
  {
    "fileName": "arrow-up-circle-solid",
    "importName": "ArrowUpCircleSolid"
  },
  {
    "fileName": "arrow-up-down",
    "importName": "ArrowUpDown"
  },
  {
    "fileName": "arrow-up-mini",
    "importName": "ArrowUpMini"
  },
  {
    "fileName": "arrow-up-right-micro",
    "importName": "ArrowUpRightMicro"
  },
  {
    "fileName": "arrow-up-right-mini",
    "importName": "ArrowUpRightMini"
  },
  {
    "fileName": "arrow-up-right-on-box",
    "importName": "ArrowUpRightOnBox"
  },
  {
    "fileName": "arrow-up-tray",
    "importName": "ArrowUpTray"
  },
  {
    "fileName": "arrow-uturn-left",
    "importName": "ArrowUturnLeft"
  },
  {
    "fileName": "arrows-pointing-out-mini",
    "importName": "ArrowsPointingOutMini"
  },
  {
    "fileName": "arrows-pointing-out",
    "importName": "ArrowsPointingOut"
  },
  {
    "fileName": "arrows-reduce-diagonal",
    "importName": "ArrowsReduceDiagonal"
  },
  {
    "fileName": "astro",
    "importName": "Astro"
  },
  {
    "fileName": "at-symbol",
    "importName": "AtSymbol"
  },
  {
    "fileName": "backward-solid",
    "importName": "BackwardSolid"
  },
  {
    "fileName": "badge-check",
    "importName": "BadgeCheck"
  },
  {
    "fileName": "bars-arrow-down",
    "importName": "BarsArrowDown"
  },
  {
    "fileName": "bars-three",
    "importName": "BarsThree"
  },
  {
    "fileName": "beaker",
    "importName": "Beaker"
  },
  {
    "fileName": "bell-alert-done",
    "importName": "BellAlertDone"
  },
  {
    "fileName": "bell-alert-solid",
    "importName": "BellAlertSolid"
  },
  {
    "fileName": "bell-alert",
    "importName": "BellAlert"
  },
  {
    "fileName": "bloom-badge",
    "importName": "BloomBadge"
  },
  {
    "fileName": "bloom",
    "importName": "Bloom"
  },
  {
    "fileName": "bolt-solid",
    "importName": "BoltSolid"
  },
  {
    "fileName": "bolt",
    "importName": "Bolt"
  },
  {
    "fileName": "book-open",
    "importName": "BookOpen"
  },
  {
    "fileName": "book",
    "importName": "Book"
  },
  {
    "fileName": "bookmarks",
    "importName": "Bookmarks"
  },
  {
    "fileName": "bottom-to-top",
    "importName": "BottomToTop"
  },
  {
    "fileName": "brackets",
    "importName": "Brackets"
  },
  {
    "fileName": "broom-sparkle-solid",
    "importName": "BroomSparkleSolid"
  },
  {
    "fileName": "broom-sparkle",
    "importName": "BroomSparkle"
  },
  {
    "fileName": "bug-ant-solid",
    "importName": "BugAntSolid"
  },
  {
    "fileName": "bug",
    "importName": "Bug"
  },
  {
    "fileName": "building-storefront",
    "importName": "BuildingStorefront"
  },
  {
    "fileName": "building-tax",
    "importName": "BuildingTax"
  },
  {
    "fileName": "buildings-mini",
    "importName": "BuildingsMini"
  },
  {
    "fileName": "buildings-solid",
    "importName": "BuildingsSolid"
  },
  {
    "fileName": "buildings",
    "importName": "Buildings"
  },
  {
    "fileName": "button",
    "importName": "Button"
  },
  {
    "fileName": "calendar-mini",
    "importName": "CalendarMini"
  },
  {
    "fileName": "calendar-solid",
    "importName": "CalendarSolid"
  },
  {
    "fileName": "calendar",
    "importName": "Calendar"
  },
  {
    "fileName": "camera",
    "importName": "Camera"
  },
  {
    "fileName": "card-sparkle",
    "importName": "CardSparkle"
  },
  {
    "fileName": "caret-maximize-diagonal",
    "importName": "CaretMaximizeDiagonal"
  },
  {
    "fileName": "caret-minimize-diagonal",
    "importName": "CaretMinimizeDiagonal"
  },
  {
    "fileName": "cash-solid",
    "importName": "CashSolid"
  },
  {
    "fileName": "cash",
    "importName": "Cash"
  },
  {
    "fileName": "channels-solid",
    "importName": "ChannelsSolid"
  },
  {
    "fileName": "channels",
    "importName": "Channels"
  },
  {
    "fileName": "chart-activity",
    "importName": "ChartActivity"
  },
  {
    "fileName": "chart-bar",
    "importName": "ChartBar"
  },
  {
    "fileName": "chart-pie",
    "importName": "ChartPie"
  },
  {
    "fileName": "chat-bubble-left-right-solid",
    "importName": "ChatBubbleLeftRightSolid"
  },
  {
    "fileName": "chat-bubble-left-right",
    "importName": "ChatBubbleLeftRight"
  },
  {
    "fileName": "chat-bubble",
    "importName": "ChatBubble"
  },
  {
    "fileName": "check-circle-mini-solid",
    "importName": "CheckCircleMiniSolid"
  },
  {
    "fileName": "check-circle-solid",
    "importName": "CheckCircleSolid"
  },
  {
    "fileName": "check-circle",
    "importName": "CheckCircle"
  },
  {
    "fileName": "check-mini",
    "importName": "CheckMini"
  },
  {
    "fileName": "check",
    "importName": "Check"
  },
  {
    "fileName": "chef-hat",
    "importName": "ChefHat"
  },
  {
    "fileName": "chevron-double-left-mini-solid",
    "importName": "ChevronDoubleLeftMiniSolid"
  },
  {
    "fileName": "chevron-double-left",
    "importName": "ChevronDoubleLeft"
  },
  {
    "fileName": "chevron-double-right-mini-solid",
    "importName": "ChevronDoubleRightMiniSolid"
  },
  {
    "fileName": "chevron-double-right",
    "importName": "ChevronDoubleRight"
  },
  {
    "fileName": "chevron-down-mini",
    "importName": "ChevronDownMini"
  },
  {
    "fileName": "chevron-down",
    "importName": "ChevronDown"
  },
  {
    "fileName": "chevron-left-mini",
    "importName": "ChevronLeftMini"
  },
  {
    "fileName": "chevron-left",
    "importName": "ChevronLeft"
  },
  {
    "fileName": "chevron-right-mini",
    "importName": "ChevronRightMini"
  },
  {
    "fileName": "chevron-right",
    "importName": "ChevronRight"
  },
  {
    "fileName": "chevron-up-down",
    "importName": "ChevronUpDown"
  },
  {
    "fileName": "chevron-up-mini",
    "importName": "ChevronUpMini"
  },
  {
    "fileName": "circle-arrow-up",
    "importName": "CircleArrowUp"
  },
  {
    "fileName": "circle-check-solid",
    "importName": "CircleCheckSolid"
  },
  {
    "fileName": "circle-dotted-line",
    "importName": "CircleDottedLine"
  },
  {
    "fileName": "circle-filled-solid",
    "importName": "CircleFilledSolid"
  },
  {
    "fileName": "circle-half-dotted-clock",
    "importName": "CircleHalfDottedClock"
  },
  {
    "fileName": "circle-half-solid",
    "importName": "CircleHalfSolid"
  },
  {
    "fileName": "circle-info-solid",
    "importName": "CircleInfoSolid"
  },
  {
    "fileName": "circle-mini-filled-solid",
    "importName": "CircleMiniFilledSolid"
  },
  {
    "fileName": "circle-mini-solid",
    "importName": "CircleMiniSolid"
  },
  {
    "fileName": "circle-minus-solid",
    "importName": "CircleMinusSolid"
  },
  {
    "fileName": "circle-plus",
    "importName": "CirclePlus"
  },
  {
    "fileName": "circle-quarter-solid",
    "importName": "CircleQuarterSolid"
  },
  {
    "fileName": "circle-sliders",
    "importName": "CircleSliders"
  },
  {
    "fileName": "circle-solid",
    "importName": "CircleSolid"
  },
  {
    "fileName": "circle-stack-solid",
    "importName": "CircleStackSolid"
  },
  {
    "fileName": "circle-stack",
    "importName": "CircleStack"
  },
  {
    "fileName": "circle-three-quarters-solid",
    "importName": "CircleThreeQuartersSolid"
  },
  {
    "fileName": "circle-warning-solid",
    "importName": "CircleWarningSolid"
  },
  {
    "fileName": "circle-xmark-solid",
    "importName": "CircleXmarkSolid"
  },
  {
    "fileName": "clock-changed-solid-mini",
    "importName": "ClockChangedSolidMini"
  },
  {
    "fileName": "clock-solid-mini",
    "importName": "ClockSolidMini"
  },
  {
    "fileName": "clock-solid",
    "importName": "ClockSolid"
  },
  {
    "fileName": "clock",
    "importName": "Clock"
  },
  {
    "fileName": "clone-dashed",
    "importName": "CloneDashed"
  },
  {
    "fileName": "cloud-arrow-down",
    "importName": "CloudArrowDown"
  },
  {
    "fileName": "cloud-arrow-up",
    "importName": "CloudArrowUp"
  },
  {
    "fileName": "cloud-solid",
    "importName": "CloudSolid"
  },
  {
    "fileName": "code-branch",
    "importName": "CodeBranch"
  },
  {
    "fileName": "code-commit",
    "importName": "CodeCommit"
  },
  {
    "fileName": "code-compare",
    "importName": "CodeCompare"
  },
  {
    "fileName": "code-editor",
    "importName": "CodeEditor"
  },
  {
    "fileName": "code-merge",
    "importName": "CodeMerge"
  },
  {
    "fileName": "code-pull-request",
    "importName": "CodePullRequest"
  },
  {
    "fileName": "code",
    "importName": "Code"
  },
  {
    "fileName": "cog-six-tooth-solid",
    "importName": "CogSixToothSolid"
  },
  {
    "fileName": "cog-six-tooth",
    "importName": "CogSixTooth"
  },
  {
    "fileName": "collapse",
    "importName": "Collapse"
  },
  {
    "fileName": "command-line-solid",
    "importName": "CommandLineSolid"
  },
  {
    "fileName": "command-line",
    "importName": "CommandLine"
  },
  {
    "fileName": "component-solid",
    "importName": "ComponentSolid"
  },
  {
    "fileName": "component",
    "importName": "Component"
  },
  {
    "fileName": "computer-desktop-solid",
    "importName": "ComputerDesktopSolid"
  },
  {
    "fileName": "computer-desktop",
    "importName": "ComputerDesktop"
  },
  {
    "fileName": "contentful",
    "importName": "Contentful"
  },
  {
    "fileName": "credit-card-refresh",
    "importName": "CreditCardRefresh"
  },
  {
    "fileName": "credit-card-solid",
    "importName": "CreditCardSolid"
  },
  {
    "fileName": "credit-card",
    "importName": "CreditCard"
  },
  {
    "fileName": "cube-solid",
    "importName": "CubeSolid"
  },
  {
    "fileName": "currency-dollar-solid",
    "importName": "CurrencyDollarSolid"
  },
  {
    "fileName": "currency-dollar",
    "importName": "CurrencyDollar"
  },
  {
    "fileName": "cursor-arrow-rays",
    "importName": "CursorArrowRays"
  },
  {
    "fileName": "cursor-default-solid",
    "importName": "CursorDefaultSolid"
  },
  {
    "fileName": "cursor-default",
    "importName": "CursorDefault"
  },
  {
    "fileName": "decision-process",
    "importName": "DecisionProcess"
  },
  {
    "fileName": "descending-sorting",
    "importName": "DescendingSorting"
  },
  {
    "fileName": "directions",
    "importName": "Directions"
  },
  {
    "fileName": "discord",
    "importName": "Discord"
  },
  {
    "fileName": "document-series",
    "importName": "DocumentSeries"
  },
  {
    "fileName": "document-text-solid",
    "importName": "DocumentTextSolid"
  },
  {
    "fileName": "document-text",
    "importName": "DocumentText"
  },
  {
    "fileName": "dots-six",
    "importName": "DotsSix"
  },
  {
    "fileName": "draft orders",
    "importName": "DraftOrders"
  },
  {
    "fileName": "drop-cap",
    "importName": "DropCap"
  },
  {
    "fileName": "ellipse-blue-solid",
    "importName": "EllipseBlueSolid"
  },
  {
    "fileName": "ellipse-green-solid",
    "importName": "EllipseGreenSolid"
  },
  {
    "fileName": "ellipse-grey-solid",
    "importName": "EllipseGreySolid"
  },
  {
    "fileName": "ellipse-mini-solid",
    "importName": "EllipseMiniSolid"
  },
  {
    "fileName": "ellipse-orange-solid",
    "importName": "EllipseOrangeSolid"
  },
  {
    "fileName": "ellipse-purple-solid",
    "importName": "EllipsePurpleSolid"
  },
  {
    "fileName": "ellipse-red-solid",
    "importName": "EllipseRedSolid"
  },
  {
    "fileName": "ellipse-solid",
    "importName": "EllipseSolid"
  },
  {
    "fileName": "ellipsis-horizontal",
    "importName": "EllipsisHorizontal"
  },
  {
    "fileName": "ellipsis-vertical",
    "importName": "EllipsisVertical"
  },
  {
    "fileName": "envelope-content",
    "importName": "EnvelopeContent"
  },
  {
    "fileName": "envelope-solid",
    "importName": "EnvelopeSolid"
  },
  {
    "fileName": "envelope",
    "importName": "Envelope"
  },
  {
    "fileName": "equals",
    "importName": "Equals"
  },
  {
    "fileName": "exclamation-circle-solid",
    "importName": "ExclamationCircleSolid"
  },
  {
    "fileName": "exclamation-circle",
    "importName": "ExclamationCircle"
  },
  {
    "fileName": "expand",
    "importName": "Expand"
  },
  {
    "fileName": "eye-mini",
    "importName": "EyeMini"
  },
  {
    "fileName": "eye-slash-mini",
    "importName": "EyeSlashMini"
  },
  {
    "fileName": "eye-slash",
    "importName": "EyeSlash"
  },
  {
    "fileName": "eye",
    "importName": "Eye"
  },
  {
    "fileName": "face-crossed-out-eyes",
    "importName": "FaceCrossedOutEyes"
  },
  {
    "fileName": "face-disappointed",
    "importName": "FaceDisappointed"
  },
  {
    "fileName": "face-smile",
    "importName": "FaceSmile"
  },
  {
    "fileName": "facebook",
    "importName": "Facebook"
  },
  {
    "fileName": "featured-badge",
    "importName": "FeaturedBadge"
  },
  {
    "fileName": "figma",
    "importName": "Figma"
  },
  {
    "fileName": "file-plus",
    "importName": "FilePlus"
  },
  {
    "fileName": "file",
    "importName": "File"
  },
  {
    "fileName": "fire-solid",
    "importName": "FireSolid"
  },
  {
    "fileName": "fire",
    "importName": "Fire"
  },
  {
    "fileName": "flag-mini",
    "importName": "FlagMini"
  },
  {
    "fileName": "floppy-disk",
    "importName": "FloppyDisk"
  },
  {
    "fileName": "flying-box",
    "importName": "FlyingBox"
  },
  {
    "fileName": "focus",
    "importName": "Focus"
  },
  {
    "fileName": "folder-illustration",
    "importName": "FolderIllustration"
  },
  {
    "fileName": "folder-open-illustration",
    "importName": "FolderOpenIllustration"
  },
  {
    "fileName": "folder-open",
    "importName": "FolderOpen"
  },
  {
    "fileName": "folder",
    "importName": "Folder"
  },
  {
    "fileName": "forward-solid",
    "importName": "ForwardSolid"
  },
  {
    "fileName": "funnel-plus",
    "importName": "FunnelPlus"
  },
  {
    "fileName": "funnel",
    "importName": "Funnel"
  },
  {
    "fileName": "gap",
    "importName": "Gap"
  },
  {
    "fileName": "gatsby-ex",
    "importName": "GatsbyEx"
  },
  {
    "fileName": "gatsby",
    "importName": "Gatsby"
  },
  {
    "fileName": "gauge-sparkle",
    "importName": "GaugeSparkle"
  },
  {
    "fileName": "ghost-worried",
    "importName": "GhostWorried"
  },
  {
    "fileName": "gift cards",
    "importName": "GiftCards"
  },
  {
    "fileName": "gift-solid",
    "importName": "GiftSolid"
  },
  {
    "fileName": "gift",
    "importName": "Gift"
  },
  {
    "fileName": "github",
    "importName": "Github"
  },
  {
    "fileName": "glasses",
    "importName": "Glasses"
  },
  {
    "fileName": "globe-europe-solid",
    "importName": "GlobeEuropeSolid"
  },
  {
    "fileName": "globe-europe",
    "importName": "GlobeEurope"
  },
  {
    "fileName": "globe",
    "importName": "Globe"
  },
  {
    "fileName": "google",
    "importName": "Google"
  },
  {
    "fileName": "grid-layout",
    "importName": "GridLayout"
  },
  {
    "fileName": "grid-list",
    "importName": "GridList"
  },
  {
    "fileName": "hand-truck",
    "importName": "HandTruck"
  },
  {
    "fileName": "hashtag",
    "importName": "Hashtag"
  },
  {
    "fileName": "heart-broken",
    "importName": "HeartBroken"
  },
  {
    "fileName": "heart",
    "importName": "Heart"
  },
  {
    "fileName": "history",
    "importName": "History"
  },
  {
    "fileName": "house-star",
    "importName": "HouseStar"
  },
  {
    "fileName": "house",
    "importName": "House"
  },
  {
    "fileName": "id-badge",
    "importName": "IdBadge"
  },
  {
    "fileName": "image-sparkle",
    "importName": "ImageSparkle"
  },
  {
    "fileName": "image",
    "importName": "Image"
  },
  {
    "fileName": "images",
    "importName": "Images"
  },
  {
    "fileName": "inbox-solid",
    "importName": "InboxSolid"
  },
  {
    "fileName": "information-circle-solid",
    "importName": "InformationCircleSolid"
  },
  {
    "fileName": "information-circle",
    "importName": "InformationCircle"
  },
  {
    "fileName": "javascript-ex",
    "importName": "JavascriptEx"
  },
  {
    "fileName": "javascript",
    "importName": "Javascript"
  },
  {
    "fileName": "key-solid",
    "importName": "KeySolid"
  },
  {
    "fileName": "key",
    "importName": "Key"
  },
  {
    "fileName": "keyboard",
    "importName": "Keyboard"
  },
  {
    "fileName": "klarna-ex",
    "importName": "KlarnaEx"
  },
  {
    "fileName": "klarna",
    "importName": "Klarna"
  },
  {
    "fileName": "klaviyo",
    "importName": "Klaviyo"
  },
  {
    "fileName": "language",
    "importName": "Language"
  },
  {
    "fileName": "laptop-mobile",
    "importName": "LaptopMobile"
  },
  {
    "fileName": "layers-3",
    "importName": "Layers3"
  },
  {
    "fileName": "layout-bottom",
    "importName": "LayoutBottom"
  },
  {
    "fileName": "layout-left-right",
    "importName": "LayoutLeftRight"
  },
  {
    "fileName": "layout-left",
    "importName": "LayoutLeft"
  },
  {
    "fileName": "layout-right",
    "importName": "LayoutRight"
  },
  {
    "fileName": "layout-top-bottom",
    "importName": "LayoutTopBottom"
  },
  {
    "fileName": "layout-top",
    "importName": "LayoutTop"
  },
  {
    "fileName": "levels",
    "importName": "Levels"
  },
  {
    "fileName": "lifebuoy",
    "importName": "Lifebuoy"
  },
  {
    "fileName": "light-bulb-solid",
    "importName": "LightBulbSolid"
  },
  {
    "fileName": "light-bulb",
    "importName": "LightBulb"
  },
  {
    "fileName": "linear",
    "importName": "Linear"
  },
  {
    "fileName": "link",
    "importName": "Link"
  },
  {
    "fileName": "linkedin",
    "importName": "Linkedin"
  },
  {
    "fileName": "list-bullet",
    "importName": "ListBullet"
  },
  {
    "fileName": "list-checkbox",
    "importName": "ListCheckbox"
  },
  {
    "fileName": "list-tree",
    "importName": "ListTree"
  },
  {
    "fileName": "loader",
    "importName": "Loader"
  },
  {
    "fileName": "lock-closed-solid-mini",
    "importName": "LockClosedSolidMini"
  },
  {
    "fileName": "lock-closed-solid",
    "importName": "LockClosedSolid"
  },
  {
    "fileName": "lock-open-solid",
    "importName": "LockOpenSolid"
  },
  {
    "fileName": "magnifier-alert",
    "importName": "MagnifierAlert"
  },
  {
    "fileName": "magnifying-glass-mini",
    "importName": "MagnifyingGlassMini"
  },
  {
    "fileName": "magnifying-glass",
    "importName": "MagnifyingGlass"
  },
  {
    "fileName": "mailbox",
    "importName": "Mailbox"
  },
  {
    "fileName": "map-pin",
    "importName": "MapPin"
  },
  {
    "fileName": "map",
    "importName": "Map"
  },
  {
    "fileName": "margin-bottom",
    "importName": "MarginBottom"
  },
  {
    "fileName": "margin-left-right",
    "importName": "MarginLeftRight"
  },
  {
    "fileName": "margin-left",
    "importName": "MarginLeft"
  },
  {
    "fileName": "margin-right",
    "importName": "MarginRight"
  },
  {
    "fileName": "margin-top-bottom",
    "importName": "MarginTopBottom"
  },
  {
    "fileName": "margin-top",
    "importName": "MarginTop"
  },
  {
    "fileName": "markdown-solid",
    "importName": "MarkdownSolid"
  },
  {
    "fileName": "mastercard",
    "importName": "Mastercard"
  },
  {
    "fileName": "media-play",
    "importName": "MediaPlay"
  },
  {
    "fileName": "media-stop-solid",
    "importName": "MediaStopSolid"
  },
  {
    "fileName": "meilisearch",
    "importName": "Meilisearch"
  },
  {
    "fileName": "member-bronze-badge",
    "importName": "MemberBronzeBadge"
  },
  {
    "fileName": "member-gold-badge",
    "importName": "MemberGoldBadge"
  },
  {
    "fileName": "member-silver-badge",
    "importName": "MemberSilverBadge"
  },
  {
    "fileName": "message-plus",
    "importName": "MessagePlus"
  },
  {
    "fileName": "meta",
    "importName": "Meta"
  },
  {
    "fileName": "microchip",
    "importName": "Microchip"
  },
  {
    "fileName": "minus-badge",
    "importName": "MinusBadge"
  },
  {
    "fileName": "minus-circle",
    "importName": "MinusCircle"
  },
  {
    "fileName": "minus-mini",
    "importName": "MinusMini"
  },
  {
    "fileName": "minus",
    "importName": "Minus"
  },
  {
    "fileName": "moon-solid",
    "importName": "MoonSolid"
  },
  {
    "fileName": "moon",
    "importName": "Moon"
  },
  {
    "fileName": "newspaper",
    "importName": "Newspaper"
  },
  {
    "fileName": "next-js",
    "importName": "NextJs"
  },
  {
    "fileName": "open-rect-arrow-out",
    "importName": "OpenRectArrowOut"
  },
  {
    "fileName": "palette",
    "importName": "Palette"
  },
  {
    "fileName": "paper-clip",
    "importName": "PaperClip"
  },
  {
    "fileName": "paper-plane",
    "importName": "PaperPlane"
  },
  {
    "fileName": "party",
    "importName": "Party"
  },
  {
    "fileName": "pause-solid",
    "importName": "PauseSolid"
  },
  {
    "fileName": "pause",
    "importName": "Pause"
  },
  {
    "fileName": "paypal",
    "importName": "Paypal"
  },
  {
    "fileName": "payphone",
    "importName": "Payphone"
  },
  {
    "fileName": "pen-plus",
    "importName": "PenPlus"
  },
  {
    "fileName": "pencil-square-solid",
    "importName": "PencilSquareSolid"
  },
  {
    "fileName": "pencil-square",
    "importName": "PencilSquare"
  },
  {
    "fileName": "pencil",
    "importName": "Pencil"
  },
  {
    "fileName": "phone",
    "importName": "Phone"
  },
  {
    "fileName": "photo-solid",
    "importName": "PhotoSolid"
  },
  {
    "fileName": "photo",
    "importName": "Photo"
  },
  {
    "fileName": "pin-tack-solid",
    "importName": "PinTackSolid"
  },
  {
    "fileName": "pin-tack",
    "importName": "PinTack"
  },
  {
    "fileName": "play-mini-solid",
    "importName": "PlayMiniSolid"
  },
  {
    "fileName": "play-solid",
    "importName": "PlaySolid"
  },
  {
    "fileName": "plug",
    "importName": "Plug"
  },
  {
    "fileName": "plus-mini",
    "importName": "PlusMini"
  },
  {
    "fileName": "plus",
    "importName": "Plus"
  },
  {
    "fileName": "pointer-circle-solid",
    "importName": "PointerCircleSolid"
  },
  {
    "fileName": "pointer",
    "importName": "Pointer"
  },
  {
    "fileName": "progress-0",
    "importName": "Progress0"
  },
  {
    "fileName": "progress-100",
    "importName": "Progress100"
  },
  {
    "fileName": "progress-15",
    "importName": "Progress15"
  },
  {
    "fileName": "progress-30",
    "importName": "Progress30"
  },
  {
    "fileName": "progress-45",
    "importName": "Progress45"
  },
  {
    "fileName": "progress-60",
    "importName": "Progress60"
  },
  {
    "fileName": "progress-75",
    "importName": "Progress75"
  },
  {
    "fileName": "progress-90",
    "importName": "Progress90"
  },
  {
    "fileName": "puzzle-solid",
    "importName": "PuzzleSolid"
  },
  {
    "fileName": "puzzle",
    "importName": "Puzzle"
  },
  {
    "fileName": "question-mark-circle",
    "importName": "QuestionMarkCircle"
  },
  {
    "fileName": "question-mark",
    "importName": "QuestionMark"
  },
  {
    "fileName": "queue-list",
    "importName": "QueueList"
  },
  {
    "fileName": "queue-solid",
    "importName": "QueueSolid"
  },
  {
    "fileName": "react-js-ex",
    "importName": "ReactJsEx"
  },
  {
    "fileName": "react-js",
    "importName": "ReactJs"
  },
  {
    "fileName": "receipt-percent",
    "importName": "ReceiptPercent"
  },
  {
    "fileName": "receipt",
    "importName": "Receipt"
  },
  {
    "fileName": "reduce",
    "importName": "Reduce"
  },
  {
    "fileName": "rename",
    "importName": "Rename"
  },
  {
    "fileName": "replay-solid",
    "importName": "ReplaySolid"
  },
  {
    "fileName": "resend",
    "importName": "Resend"
  },
  {
    "fileName": "resize",
    "importName": "Resize"
  },
  {
    "fileName": "robot",
    "importName": "Robot"
  },
  {
    "fileName": "rocket-launch-solid",
    "importName": "RocketLaunchSolid"
  },
  {
    "fileName": "rocket-launch",
    "importName": "RocketLaunch"
  },
  {
    "fileName": "rss",
    "importName": "Rss"
  },
  {
    "fileName": "sanity",
    "importName": "Sanity"
  },
  {
    "fileName": "sap",
    "importName": "Sap"
  },
  {
    "fileName": "scan-text",
    "importName": "ScanText"
  },
  {
    "fileName": "scan",
    "importName": "Scan"
  },
  {
    "fileName": "scroll-text",
    "importName": "ScrollText"
  },
  {
    "fileName": "sendgrid",
    "importName": "Sendgrid"
  },
  {
    "fileName": "server-solid",
    "importName": "ServerSolid"
  },
  {
    "fileName": "server-stack-solid",
    "importName": "ServerStackSolid"
  },
  {
    "fileName": "server-stack",
    "importName": "ServerStack"
  },
  {
    "fileName": "server",
    "importName": "Server"
  },
  {
    "fileName": "share",
    "importName": "Share"
  },
  {
    "fileName": "shield-check",
    "importName": "ShieldCheck"
  },
  {
    "fileName": "shipbob",
    "importName": "Shipbob"
  },
  {
    "fileName": "shippo",
    "importName": "Shippo"
  },
  {
    "fileName": "shopping-bag",
    "importName": "ShoppingBag"
  },
  {
    "fileName": "shopping-cart-solid",
    "importName": "ShoppingCartSolid"
  },
  {
    "fileName": "shopping-cart",
    "importName": "ShoppingCart"
  },
  {
    "fileName": "shopping",
    "importName": "Shopping"
  },
  {
    "fileName": "sidebar-left-filled",
    "importName": "SidebarLeftFilled"
  },
  {
    "fileName": "sidebar-left",
    "importName": "SidebarLeft"
  },
  {
    "fileName": "sidebar-right-filled",
    "importName": "SidebarRightFilled"
  },
  {
    "fileName": "sidebar-right",
    "importName": "SidebarRight"
  },
  {
    "fileName": "slack",
    "importName": "Slack"
  },
  {
    "fileName": "snooze",
    "importName": "Snooze"
  },
  {
    "fileName": "sparkle-2-solid",
    "importName": "Sparkle2Solid"
  },
  {
    "fileName": "sparkles-mini-solid",
    "importName": "SparklesMiniSolid"
  },
  {
    "fileName": "sparkles-mini",
    "importName": "SparklesMini"
  },
  {
    "fileName": "sparkles-solid",
    "importName": "SparklesSolid"
  },
  {
    "fileName": "sparkles",
    "importName": "Sparkles"
  },
  {
    "fileName": "spinner",
    "importName": "Spinner"
  },
  {
    "fileName": "square-blue-solid",
    "importName": "SquareBlueSolid"
  },
  {
    "fileName": "square-dashed-cursor",
    "importName": "SquareDashedCursor"
  },
  {
    "fileName": "square-green-solid",
    "importName": "SquareGreenSolid"
  },
  {
    "fileName": "square-grey-solid",
    "importName": "SquareGreySolid"
  },
  {
    "fileName": "square-orange-solid",
    "importName": "SquareOrangeSolid"
  },
  {
    "fileName": "square-purple-solid",
    "importName": "SquarePurpleSolid"
  },
  {
    "fileName": "square-red-solid",
    "importName": "SquareRedSolid"
  },
  {
    "fileName": "square-two-stack-mini",
    "importName": "SquareTwoStackMini"
  },
  {
    "fileName": "square-two-stack-solid",
    "importName": "SquareTwoStackSolid"
  },
  {
    "fileName": "square-two-stack",
    "importName": "SquareTwoStack"
  },
  {
    "fileName": "squares-plus-solid",
    "importName": "SquaresPlusSolid"
  },
  {
    "fileName": "squares-plus",
    "importName": "SquaresPlus"
  },
  {
    "fileName": "stack-perspective",
    "importName": "StackPerspective"
  },
  {
    "fileName": "star-solid",
    "importName": "StarSolid"
  },
  {
    "fileName": "star",
    "importName": "Star"
  },
  {
    "fileName": "stop-circle-solid",
    "importName": "StopCircleSolid"
  },
  {
    "fileName": "stopwatch",
    "importName": "Stopwatch"
  },
  {
    "fileName": "store credits",
    "importName": "StoreCredits"
  },
  {
    "fileName": "stripe",
    "importName": "Stripe"
  },
  {
    "fileName": "sun-solid",
    "importName": "SunSolid"
  },
  {
    "fileName": "sun",
    "importName": "Sun"
  },
  {
    "fileName": "svelte",
    "importName": "Svelte"
  },
  {
    "fileName": "swatch-solid",
    "importName": "SwatchSolid"
  },
  {
    "fileName": "swatch",
    "importName": "Swatch"
  },
  {
    "fileName": "table-pen",
    "importName": "TablePen"
  },
  {
    "fileName": "tablet",
    "importName": "Tablet"
  },
  {
    "fileName": "tag-illustration",
    "importName": "TagIllustration"
  },
  {
    "fileName": "tag-solid",
    "importName": "TagSolid"
  },
  {
    "fileName": "tag",
    "importName": "Tag"
  },
  {
    "fileName": "tailwind",
    "importName": "Tailwind"
  },
  {
    "fileName": "tanstack",
    "importName": "Tanstack"
  },
  {
    "fileName": "target",
    "importName": "Target"
  },
  {
    "fileName": "tax-exclusive",
    "importName": "TaxExclusive"
  },
  {
    "fileName": "tax-inclusive",
    "importName": "TaxInclusive"
  },
  {
    "fileName": "telegram",
    "importName": "Telegram"
  },
  {
    "fileName": "telescope-solid",
    "importName": "TelescopeSolid"
  },
  {
    "fileName": "telescope",
    "importName": "Telescope"
  },
  {
    "fileName": "text-highlight",
    "importName": "TextHighlight"
  },
  {
    "fileName": "text",
    "importName": "Text"
  },
  {
    "fileName": "thumb-down",
    "importName": "ThumbDown"
  },
  {
    "fileName": "thumb-up",
    "importName": "ThumbUp"
  },
  {
    "fileName": "thumbnail-badge",
    "importName": "ThumbnailBadge"
  },
  {
    "fileName": "timeline-vertical",
    "importName": "TimelineVertical"
  },
  {
    "fileName": "tools-solid",
    "importName": "ToolsSolid"
  },
  {
    "fileName": "tools",
    "importName": "Tools"
  },
  {
    "fileName": "top-to-bottom",
    "importName": "TopToBottom"
  },
  {
    "fileName": "trash",
    "importName": "Trash"
  },
  {
    "fileName": "triangle-down-mini",
    "importName": "TriangleDownMini"
  },
  {
    "fileName": "triangle-left-mini",
    "importName": "TriangleLeftMini"
  },
  {
    "fileName": "triangle-right-mini-hover",
    "importName": "TriangleRightMiniHover"
  },
  {
    "fileName": "triangle-right-mini",
    "importName": "TriangleRightMini"
  },
  {
    "fileName": "triangle-up-mini",
    "importName": "TriangleUpMini"
  },
  {
    "fileName": "triangles-mini",
    "importName": "TrianglesMini"
  },
  {
    "fileName": "trophy",
    "importName": "Trophy"
  },
  {
    "fileName": "truck-fast",
    "importName": "TruckFast"
  },
  {
    "fileName": "typescript-ex",
    "importName": "TypescriptEx"
  },
  {
    "fileName": "typescript",
    "importName": "Typescript"
  },
  {
    "fileName": "typography",
    "importName": "Typography"
  },
  {
    "fileName": "unfold",
    "importName": "Unfold"
  },
  {
    "fileName": "user-group",
    "importName": "UserGroup"
  },
  {
    "fileName": "user-mini",
    "importName": "UserMini"
  },
  {
    "fileName": "user",
    "importName": "User"
  },
  {
    "fileName": "users-solid",
    "importName": "UsersSolid"
  },
  {
    "fileName": "users",
    "importName": "Users"
  },
  {
    "fileName": "variable",
    "importName": "Variable"
  },
  {
    "fileName": "vercel",
    "importName": "Vercel"
  },
  {
    "fileName": "verified-badge",
    "importName": "VerifiedBadge"
  },
  {
    "fileName": "visa",
    "importName": "Visa"
  },
  {
    "fileName": "vite",
    "importName": "Vite"
  },
  {
    "fileName": "wand-sparkle",
    "importName": "WandSparkle"
  },
  {
    "fileName": "webshipper",
    "importName": "Webshipper"
  },
  {
    "fileName": "window",
    "importName": "Window"
  },
  {
    "fileName": "wish lists",
    "importName": "WishLists"
  },
  {
    "fileName": "wrench",
    "importName": "Wrench"
  },
  {
    "fileName": "x-circle-solid",
    "importName": "XCircleSolid"
  },
  {
    "fileName": "x-circle",
    "importName": "XCircle"
  },
  {
    "fileName": "x-mark-mini",
    "importName": "XMarkMini"
  },
  {
    "fileName": "x-mark",
    "importName": "XMark"
  },
  {
    "fileName": "x",
    "importName": "X"
  }
]

export const categories = [...new Set(componentRegistry.map((c) => c.category))].sort()
