/**
 * Shared utilities for auto-discovery scripts.
 */

/**
 * Convert kebab-case to PascalCase.
 * @param {string} str - e.g. "arrow-down"
 * @returns {string} - e.g. "ArrowDown"
 */
export function kebabToPascal(str) {
  return str
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")
}

/**
 * Auto-generated file header comment.
 * @param {string} scriptName
 * @returns {string}
 */
export function autoGenHeader(scriptName) {
  return `/**
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by scripts/${scriptName}
 * Run \`npm run generate\` to regenerate.
 */`
}
